### ISSUE TITLE
Improve "Record Starts With"

### ISSUE THREAD

**Issue by jeff-bowles** [shriprem/FWDataViz#2]
Hi - I'll start by saying this is a fantastic, wonderful plugin!  I work with lots of flat file data exchange formats and this will be a great time saver.

Possibly this feature already exists and I just have not found it yet.

My request:

One of the formats I work with has record identifiers not in the first text column, but in the fourth through seventh character positions.  It would seem that the "Record Regex Key" alone should be enough to identify the record type, and the "Record Starts With" does not understand regex.

Is there an existing way to identify records that don't "start with" but "contain at position"?  If not, would you consider adding this feature?

Thank you,

Jeff

**Comment by shriprem** [comment]
@jeff-bowles, please see the *GSN-Flagged Weather Stations* sample file provided with the plugin. You can find it under _Sample Files » Sample Multiple-Record-Type Files_. This sample has two record types:
1.  GSN Weather Station. Record Regex Key: `^.{72}GSN`
2. Non-GSN Weather Station. Record Regex Key: `^.{72}[^G]`

You will note that for both these record types, the _Record Starts With_ field is blank in the metadata editor and the .ini file. The _Record Starts With_ is a convenience field for users. As this field is being input, it is immediately translated into the _Record Regex Key_ field value. This Regex Key value is the one actually used by the plugin to visualize files.

The plugin's metadata editor does a reverse translation of the _Record Regex Key_ field changes to the _Record Starts With_ value only when possible. If the regex key is not based on the initial characters alone, it leaves the _Record Starts With_ field blank.

If your record-type is going to be based solely on the regex key, you can leave the _Record Starts With_ field blank.

Hope this clarifies your issue.

**Comment by shriprem** [comment]
Also, see _ICD-10 Billable_Flagged Order Codes_ sample file. In this file, an order is deemed billable or not by the presence of '1' (billable) or '0' (non-billable) in the 15th position of each order record. The regex key used here is `^.{14}1` and `^.{14}0`, respectively.

@jeff-bowles , unless I hear otherwise in the next 24 hours, I will deem this issue needs no further resolution, and will close it.

**Comment by jeff-bowles** [comment]
Thank you so much, Shridhar.  This is working as I wish.  I think my 
first attempt I simply had bad regex expressions.

------ Original Message ------

**Comment by shriprem** [comment]
Jeff, thank you for your kind compliments. Glad to have helped.
