### ISSUE TITLE
The visualizer doesn't look nice with dark mode / dark themes

### ISSUE THREAD

**Issue by rasmusgreve** [shriprem/FWDataViz#20]
The visualizer doesn't look very nice when a dark theme has been selected. 
The line number background color seems to be overwritten:
![image](https://user-images.githubusercontent.com/1412376/128010216-6864df12-9342-4cc9-9762-0322f1d5b06f.png)

**Comment by shriprem** [comment]
Thank you for noticing this issue and reporting it here. I have a fix for this issue at the [1.4.2.1-beta release](https://github.com/shriprem/FWDataViz/releases/tag/1.4.2.1-beta) page.

The change needed for the fix involved just the [removal](https://github.com/shriprem/FWDataViz/commit/0f34bdae7c3d80c7203541c1e69790298d48775e#commitcomment-54364862) of a `SCI_STYLECLEARALL` call. This all-styles-clear call was, very likely, superfluous and hence its removal may not cause any regressions. If it does, please report it here.

### DLL-only manual upgrade of a previously installed version of the plugin
Go to the [1.4.2.1-beta release](https://github.com/shriprem/FWDataViz/releases/tag/1.4.2.1-beta) page. Download the zip file version to match your Notepad++ bitness. Extract the `FWDataviz.dll` file into the `<NPP_Plugins_folder>/FWDataviz` folder to overwrite the existing DLL therein.

**Comment by rasmusgreve** [comment]
Good work! This fixes the issue. Thank you!
