### ISSUE TITLE
Feature requests + bug

### ISSUE THREAD

**Issue by jeff-bowles** [shriprem/FWDataViz#3]
Hello, Sridhar

I wonder if you might consider a couple of small changes?  And thank you for a wonderful productivity tool!

1) Bug - The visualizer panel word-wraps the record type and field label even if the panel is wide enough to accommodate the string.  See screen shot.
2) Feature request - I would like to see the record length added to the panel.  Both the "designed" and "actual" record length, in case there is a discrepancy.
3) Feature request - Could you add an "auto detect" for the file type, perhaps based on a regex rule?  I work with multiple data file types, each with multiple versions, so it would be great to automatically select the right file type based on contents.
![Clipboard01](https://user-images.githubusercontent.com/32487935/110500460-36baef80-80c7-11eb-82ad-d354ab51a246.jpg)

Kind regards,
Jeff Bowles

**Comment by shriprem** [comment]
Jeff, I have implemented the first two of your feature requests. The *auto-detect* feature needs a bit more time. 

> ### Version 1.0.1.0
> #### Enhancements:
> 1. *Cursor Position Data* display will shrink or grow to the dock panel width.
> 2. Long text in *Cursor Position Data* display will scroll horizontally instead of wrapping to the next line.
> 3. Added *Record Length [Current/Defined]* line in *Cursor Position Data* display.
> 

To obtain this latest pre-release build, please go to the [Releases](https://github.com/shriprem/FWDataViz/releases) section. Download the dll zip version to match your Notepad++ bitness. Unzip it into the `<NPP_Plugins_folder>/FWDataviz` folder to overwrite the existing DLL therein.

Please let me know if you see any regression issues with this build. Appreciate your feedback.

**Comment by shriprem** [comment]
Jeff, I have implemented the _Auto-detect File Type (ADFT)_ feature. It is available in the [1.0.2.0-beta](https://github.com/shriprem/FWDataViz/releases/tag/1.0.2.0) release.

Download the zip file version to match your Notepad++ bitness. Unzip the `FWDataViz.dll` and `default_Visualizer.ini` files in the zip file into the `<NPP_Plugins_folder>/FWDataviz` folder to overwrite the existing files therein.

You will need the `default_Visualizer.ini` file to view the ADFT settings used for the sample files. Also, review usage hints at [Auto-Detect File Type Configuration](https://github.com/shriprem/FWDataViz/blob/master/docs/auto_detect_file_type.md).

Let me know if you need further clarification or if you come across any issues. Thank you for suggesting the ADFT feature. Even I have come to appreciate its utility.

**Comment by jeff-bowles** [comment]
Previously, the DLL was named FWDataViz10.dll.  Now it abbreviated to
FWDataViz.dll.  Should I remove the earlier one from the plugin folder?

**Comment by shriprem** [comment]
I am not sure how you got the FWDataViz10.dll. The plugin DLL has always been named FWDataViz.dll. The plugin will not load in Notepad++ with any other name. So, you can delete that other DLL with the odd name.

Meanwhile, I have uploaded a newer set of files for the [1.0.2.0-RC](https://github.com/shriprem/FWDataViz/releases/tag/1.0.2.0) release. This is a minor update. I have only added the _ADFT in a Nutshell_ balloon tip at the ADFT section on the File Metadata editor. I have also included [this in the online documentation](https://github.com/shriprem/FWDataViz/blob/master/docs/auto_detect_file_type.md#adft-in-a-nutshell).

**Comment by jeff-bowles** [comment]
Hello again, Shridhar.

I have installed the new DLL and tried things out.  ADFT is a really useful
feature!  If there is one thing I would change with ADFT, I find the "Line
Number" aspect somewhat restrictive.  For example, although it is most
common that a "FOO" file type will always start with a "BAR123" record on
line 1, it is possible that it starts with a "BAZ321" instead.  However, I
know that somewhere in the first 25 lines or so, a "FOO" file type will
always have a record beginning with "XYZZY".

Having said that, this is not a common condition for me.  If I had to use
the plugin as-is forever, I would still be very happy!

Please tell me how much of your time you want me to consume - I have some
more features in mind but don't want to become a pest.

Thank you,

Jeff

**Comment by shriprem** [comment]
Jeff,
The current line-number based logic allows for quick scanning of documents as they load. While testing this feature, I would open Notepad++ with 8 different files, each of a different file type. All would load with no perceptible lag. I fear that trying to cater to wide-ranging scenarios would make the ADFT user interface clunky, and introduce noticeable lags in NPP's document handling.

Even with the current line-number based ADFT, there are ways to get creative by leveraging the power of regular expressions. For example, if a line either starts with 'ABC' or 'PQR' or 'XYZ', use regex: `(ABC)|(PQR)|(XYZ)`

I was actually anticipating that you or other users would find only three ADFT expressions to be be too limiting. I went with only three for the first iteration. But I have designed the code to be able to handle more, with most of those changes confined to the UI layout. Let us see if there is such a real need for it.

Please submit your other feature requests as separate issues. I will surely look into them. If I am able to implement them, I will do so as and when my other obligations will permit.

I will be closing this issue. Thank you for your suggestion for ADFT.

**Comment by jeff-bowles** [comment]
Shridhar,

Thanks for the reply.  I've submitted three new feature requests for your
consideration.

Regards,

Jeff
