### ISSUE TITLE
Enable / Disable plugin ondemand

### ISSUE THREAD

**Issue by SullyPanda76cl** [shriprem/FWDataViz#31]
This great plugin is awesome.

An active problem is that it can't be disabled on demand, so when using parent app (Notepad++) to edit any other filetype (source code, in, etc) any other synthax highlight is override.

![npp](https://user-images.githubusercontent.com/44233071/132680654-ad4c15f4-1df2-4b26-b7ec-86605cec6b45.png)

**Comment by shriprem** [comment]
@SullyPanda76cl, please provide the version of the plugin you are using.

I had noticed this issue myself and fixed it in the 2.1.1.1 version. I have mentioned this in the [2.1.1.1 Release notes - item 1](https://github.com/shriprem/FWDataViz/releases/tag/v2.1.1.1). However, I recommend that you install the latest [2.1.2.1](https://github.com/shriprem/FWDataViz/releases/tag/v2.1.2.1) version and try it out. Thank you.

**Comment by SullyPanda76cl** [comment]
Thanks for answering.
That's another issue (i write it in the "discussion" section here) N++ is, for some reason, downloading version 1.4...
Perhaps there's some repository that's missing to update?

**Comment by shriprem** [comment]
@SullyPanda76cl , I have already [responded](https://github.com/shriprem/FWDataViz/discussions/30#discussioncomment-1298459) to your observation on the version lag of the plugin. Again, what version of the plugin gets included in N++ depends on the PR merges at [nppPluginList](https://github.com/notepad-plus-plus/nppPluginList) and the release cycle of N++. Both these are beyond my control.

You could manually upgrade the FWDataViz plugin to the latest version just by copying over the latest `FWDataViz.dll` into your N++ plugins folder.

### DLL-only manual upgrade of a previously installed version of the plugin
Go to the [2.1.2.1 Release](https://github.com/shriprem/FWDataViz/releases/tag/v2.1.2.1) page. Download the zip file version to match your Notepad++ bitness. Then, either:
1. In Notepad++, navigate to menu: _Settings » Import » Import Plugins..._ and import the dll file extracted from the zip file.
2. OR, Extract the `FWDataviz.dll` file into the `<NPP_Plugins_folder>/FWDataviz` folder to overwrite the existing DLL therein.
