### ISSUE TITLE
Multi-byte characters break highlighter/fields

### ISSUE THREAD

**Issue by rasmusgreve** [shriprem/FWDataViz#32]
Multi-byte characters break the highlighter and field definitions.
In the format that I'm currently looking at, some text fields can contain multi-byte characters (see attached image).
The two lines in the image have the same record type and field layout, but because one of the lines contains the multi-byte characters: æøå, the line is highlighted wrong.

![image](https://user-images.githubusercontent.com/1412376/137127727-bc360438-7d37-4f4c-a3d8-83b98c587c14.png)

**Comment by shriprem** [comment]
@rasmusgreve , please try out the latest [v2.3.0.0 release](https://github.com/shriprem/FWDataViz/releases/tag/v2.3.0.0) for FWDataViz. This release fully supports multi-byte characters, to include Record Terminators, ADFT Regexes & Record Markers. Also, this release features [Field Copy](https://github.com/shriprem/FWDataViz/blob/master/docs/field_copy_paste.md#field-copy), [Field Paste](https://github.com/shriprem/FWDataViz/blob/master/docs/field_copy_paste.md#field-paste) and [Field Hop](https://github.com/shriprem/FWDataViz/blob/master/docs/field_navigation.md) -- all of these also accessible via [menu-based keyboard shortcuts](https://github.com/shriprem/FWDataViz/blob/master/docs/menu_shortcuts.md).

Thank you.
