### ISSUE TITLE
NPP Plugin Version

### ISSUE THREAD

**Issue by TheSQLGuru** [shriprem/FWDataViz#42]
The version of this plugin that you get from using the Plugin Admin in NPP is 2.1.2.1, and it does not show up as having an update available.

The version here on Github is currently 2.4.0.1. 

I could find no way to replace the old version with the current build. Can you please post up how to do that and/or replace the version pulled automatically with the latest build? 

Thanks in advance!!

**Comment by shriprem** [comment]
The update information for all the NPP plugin is baked into the `<NPP_Install_Folder>/plugins/Config/nppPluginList.dll` file.

This DLL is compiled and digitally signed by the creator of NPP. And, this DLL gets updated with each new NPP version.

1. The update info for the 2.4.0.1 version of the FWDataViz plugin was first included in Notepad++ 8.2.0.0 release. Do you have this or a later version of Notepad++?
2. Maybe when you last updated your Notepad++, you only updated the files in the main folder of the NPP folder and skipped updating the nppPluginList.dll file. If you right click on this file, then _Properties_, and then the _Details_ tab:
   - The _File Version_ should be at least 1.4.2.0.
   - The _Date Modified_ should be at least 12/31/2021 (i.e., the date of the NPP 8.2.0.0 build).
![image](https://user-images.githubusercontent.com/45252729/150897753-2f5ef965-1237-4453-ad3f-743f4627386a.png)

3. If you prefer to stay on an older version of NPP but still get the updated FWDataViz plugin, go to the [2.4.0.1 Release](https://github.com/shriprem/FWDataViz/releases/tag/v2.4.0.1) page. The manual install instructions and the version zip files are both available there.

**Comment by TheSQLGuru** [comment]
Looks like you are correct on the not updating the nppPluginList.dll. My
version is 1.3.9.0, dated 20211021. I will update NPP again with the latest
build and make sure to include that part of the installation.

Thanks!

Kevin G. Boles
SQL Server Consultant
SQL Server MVP 2007 - 2012
Indicium Resources, Inc.
@TheSQLGuru
