### ISSUE TITLE
No colorization after switching to 64 bit

### ISSUE THREAD

**Issue by jeff-bowles** [shriprem/FWDataViz#45]
This is possibly an environmental issue and not a bug.

- I decided to update Notepad++ to 64-bit.
- The install offered to remove the 32-bit version (keeping settings), which I allowed.
- I downloaded the 64-bit version of FWDataViz 2.4.0.2 via the Plugins Admin Tool
- FWDataVis properly auto-detects my custom file definitions, and all the fields are still identified correctly
- The theme is still set to "Spectrum"
- No coloring is happening
- If I "View Sample Files" from the FWDataVis dialog, and choose one of the predefined files, coloring works.

Any ideas for things to try?

**Comment by shriprem** [comment]
Interesting!

I need to review your `Themes.ini` and the `Visualizer.ini` files. Please put both of them into a zip file, and attach it here in your reply post. Both .ini files can be found in the `%APPDATA%\Notepad++\plugins\Config\FWDataViz` (for _full_ installs of NPP); or in the `<NPP_Portable_path>\plugins\Config\FWDataViz` folder (for _portable_ installs of NPP). 

[Note that the `%APPDATA%` part in the full-install NPP user config path mentioned above will expand dynamically to something like: `C:\Users\jeff-bowles\AppData\Roaming\` if you were to use it either in the Windows Command Prompt or the Windows File Explorer address bar.]

**Comment by jeff-bowles** [comment]
Here are the *.ini files.

Thanks for investigating!

[FWDataViz.zip](https://github.com/shriprem/FWDataViz/files/8389716/FWDataViz.zip)

**Comment by shriprem** [comment]
@jeff-bowles , I couldn't find any obvious issues with your .ini files. You have 21 different file types defined in your Visualizer.ini. A few  of those file types are a bit more complex, with more record types, than others. Is the colorization failing with all file types? Even the simpler ones?

To try to replicate your issue, on a pristine PC, I first installed the 32-bit NPP 8.1.9.3 version. Then I upgraded it with the 64-bit NPP 8.3.3 version. The colorization feature of the FWDataViz plugin worked just as seamlessly after the 64-bit upgrade. So, without the actual data files to test further, I am at a loss to think of a cause for the issue you are describing here.

Perhaps, you might be able to isolate the problem by quickly testing against multiple, portable versions of NPP with your .ini files. From https://notepad-plus-plus.org/downloads/, download both the 32-bit & 64-bit portable zip files for versions 8.3.3, 8.2.1 & 8.1.9.3. Then unzip them all into their separate folders. In the screenshot below, I have used, for example, the default user Downloads folder.
![image](https://user-images.githubusercontent.com/45252729/161178936-a14c3399-094e-4415-9115-ec33edecbd22.png)

Then you can start testing separately with each portable version of NPP. You will need to ensure that no other version of NPP is still running when testing each version. Start with the most recent version (8.3.3), and work your way backwards. To be sure, confirm the NPP version number you are testing either by pressing the _F1_ key or the _About Notepad++_ help menu item. Download the FWDataViz plugin for each version using its Plugin Admins dialog. Then copy over your .ini files into the _FWDataViz_ subfolder in the appropriate `<NPP_Portable_path>\plugins\Config` folder. For example, for the 64-bit NPP 8.3.3 portable you see in my screenshot, the .ini files will need to be copied into `C:\Users\username\Downloads\npp.8.1.9.3.portable.x64\plugins\Config\FWDataViz\`. 

If you can replicate the colorization issue with your data files in any of these portable versions, please report it here, listing which versions passed and which failed. Thank you for your time.

**Comment by jeff-bowles** [comment]
I've been able to confirm there is nothing wrong with FWDataViz.  I think I must have some text files with some sort of corruption or perhaps an encoding issue.  Thanks for your detailed response!
