### ISSUE TITLE
Enhancement:  Allow certain fields to be hidden

### ISSUE THREAD

**Issue by jeff-bowles** [shriprem/FWDataViz#5]
It would be useful for some record types to be able to mark "filler" fields as "do not display".  Especially when these fields are near the beginning of the record.  This way, one might not have to scroll as often horizontally to view the important data fields.

This feature could also be useful at the record level.  Certain file formats contain boilerplate record types that don't really contribute information to the person reading the file.  For example, copyright notices or "authorized use only" warnings.

**Comment by shriprem** [comment]
FWDataViz is a _plugin_ that is constrained by the APIs of [Notepad++](https://npp-user-manual.org/docs/plugin-communication/) and the [Scintilla](https://www.scintilla.org/ScintillaDoc.html#MessageCategories) text control. The suggested feature will be feasible in a standalone, custom-built application for such files, but not with this plugin.
