### ISSUE TITLE
Enhancement: User-Definable tool-tips for field contents

### ISSUE THREAD

**Issue by jeff-bowles** [shriprem/FWDataViz#6]
It might be useful in some cases to be able to hover (or right-click) a field to get a balloon-help box explaining what a fizzbuzz code "FB23" means.

**Comment by shriprem** [comment]
The FWDataViz is expected to be used by a knowledge worker who is already familiar with the specifications of the file type; not by a lay person. As such, the plugin user is expected to know the significance of the field name "FB23". Moreover, the metadata editor allows up to 255 characters for field names. So an additional short hint could be incorporated within the field label. Say: `FB23 [Fire Brigade - Zone 23]`. And, such descriptive field names already display on the plugin panel.

Extending the metadata editor UI to gather tooltips for each field within a record will make the UI too complex while adding little more of value. The suggested feature might be feasible in a standalone, custom-built application, but not with this general-use plugin.
