### ISSUE TITLE
Feature request: Sequence Numbers in the 'Jump to Field' dropdown list

### ISSUE THREAD

**Issue by jeff-bowles** [shriprem/FWDataViz#72]
I would like to see field numbers in the "jump to field" picklist.
![image](https://user-images.githubusercontent.com/32487935/176715868-acae6fea-8a5c-4785-af3d-9d3e9270d5af.png)

Thanks!

**Comment by shriprem** [comment]
@jeff-bowles , this request can be implemented fairly quickly. Before I do that and provide you with a pre-release build, any feedback on the [Folding Record Blocks](https://github.com/shriprem/FWDataViz/pull/70#issuecomment-1168067560) feature? I was anticipating that by now you would have been able to go through the [brief usage notes](https://github.com/shriprem/FWDataViz/pull/70#issuecomment-1168067560) and tried out the feature with your data files.

**Comment by jeff-bowles** [comment]
By the way - I'll be travelling tomorrow and offline.  I'll check back over the weekend to see if you need anything from me.

**Comment by jeff-bowles** [comment]
Now I see that MultiLineGSN.txt is not defined for folding.  Please disregard.

I tested with IPAC_ANSI.txt and got the same behavior as icd10cm_order_2020.txt; that is where the fold points disappear upon clicking any one of them.  I also observed that switching to a different document (via the NPP tabs) and back will restore the appearance of the fold points, as will File --> "reload from disk".

**Comment by jeff-bowles** [comment]
There is also some odd behavior regarding scrolling down past the initial screenful of text.  The fold points are not visible past that first screen, unless I either switch documents and back again, or "reload from disk".

**Comment by jeff-bowles** [comment]
Hmm - maybe a good clue for you.  The "toggle line" button in the FWDataViz panel will toggle the folding on a node without making all the fold points disappear.  It will toggle back (unfold) correctly as well.
