### ISSUE TITLE
Creating new fold structures crashes Notepad++

### ISSUE THREAD

**Issue by SKlimaszewskiFDX** [shriprem/FWDataViz#84]
Creating new fold structures in the Editor frequently crashed the whole Notepad++ for me.
I can't exactly pinpoint what does that and how to reproduce it. The same action once works, then again it crashes the whole N++ (just closes the app). If I'll find any pattern to it, I'll add it here. For now it is worth investigating further.

**Comment by shriprem** [comment]
As chance would have it, I was on a long flight when you reported this bug. Hence the delay in my response here.

I have not run into this issue during my extensive usage with this feature. So, please continue to monitor for any patterns that may be causing such crashes on your system.

If you or others are able to report back with  bit more specific information on these crashes, I will remove the **_wontfix_** label on this issue and work on resolving the source of such crashes.

**Comment by shriprem** [comment]
Today, I found 3 pathways to crash Notepad++ while using the Fold Structures Editor. See issues: #99, #102, #103 

I have fixed all 3 issues. The fixes can be tested by downloading the DLL from [`Actions` » `CI_build`](https://github.com/shriprem/FWDataViz/actions/workflows/CI_build.yml). For more info, please refer to Discussion #73.
